import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const MENUS = [
  {
    href: "/",
    label: "홈",
  },
  {
    href: "/guide/hunting-ground",
    label: "사냥터",
  },
  {
    href: "/guide/equipment",
    label: "장비",
  },
  {
    href: "/guide/link-character",
    label: "링크 캐릭터",
  },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className={"mb-[16px]"}>
          <nav>
            <ul className={"flex items-center gap-x-[8px]"}>
              {MENUS.map((menu, idx) => {
                const { href, label } = menu;

                return (
                  <li key={idx}>
                    <Link href={href}>{label}</Link>
                  </li>
                );
              })}
            </ul>
          </nav>
        </header>
        <main className="flex flex-col items-center justify-between px-24">
          {children}
        </main>
      </body>
    </html>
  );
}
